FROM registry.access.redhat.com/ubi9/ubi:9.5

ENV GOOSE_BIN_DIR=/opt/goose

# Install dependencies
RUN dnf install -y bzip2 libxcb
RUN useradd goose && \
    mkdir -p $GOOSE_BIN_DIR && chown goose:goose $GOOSE_BIN_DIR

USER goose
WORKDIR /tmp

# Install Goose
RUN curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | bash

# Config Goose
COPY --chown=goose --chmod=711 scripts/goose-cli-entrypoint.sh $GOOSE_BIN_DIR/entrypoint.sh
RUN echo '${GOOSE_BIN_DIR}/goose "$@"' >> $GOOSE_BIN_DIR/entrypoint.sh

WORKDIR $GOOSE_BIN_DIR

ENTRYPOINT ["sh", "-c", "${GOOSE_BIN_DIR}/entrypoint.sh"]
CMD ["--help"]
