FROM scratch AS builder

COPY node_modules /extension/node_modules
COPY package.json icon.png LICENSE README.md /extension/
COPY dist /extension/dist

FROM scratch

LABEL org.opencontainers.image.title="Podman Desktop Agent" \
        org.opencontainers.image.description="Podman Desktop Agent" \
        org.opencontainers.image.vendor="Marc Nuri - www.marcnuri.com" \
        io.podman-desktop.api.version=">= 1.17.0"

COPY --from=builder /extension/ /extension/
