name: Publish

on:
  push:
    branches:
      - main
  pull_request: {} # TODO: remove

jobs:
  node-modules-windows-x64:
    name: 'Node Modules: Windows x64'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node Modules
        run: |
          npm install
          Move-Item -Path node_modules -Destination node_modules_windows_x64
      - name: Store Node Modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules_windows_x64
          path:
            node_modules_windows_x64
  node-modules-unix-arm64:
    name: "Node Modules: Unix ARM64"
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node Modules
        run: |
          npm install
          mv node_modules node_modules_unix_arm64
      - name: Store Node Modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules_unix_arm64
          path:
            node_modules_unix_arm64
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - node-modules-windows-x64
      - node-modules-unix-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Node Modules Windows x64
        uses: actions/download-artifact@v4
        with:
          name: node_modules_windows_x64
          path: node_modules_windows_x64
      - name: Download Node Modules Unix ARM64
        uses: actions/download-artifact@v4
        with:
          name: node_modules_unix_arm64
          path: node_modules_unix_arm64
      - name: Quay Login
        run: |
          echo ${{ secrets.QUAY_PASSWORD }} | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin
      - name: Build and Push Extension
        shell: bash
        run: |
          ./scripts/build-image.sh "quay.io/manusa/podman-desktop-agent-extension" "latest"
